"""replace_borrower_name_with_id

Revision ID: a1601601a892
Revises: 9a7a3d60e7ee
Create Date: 2026-06-25 17:32:02.011077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1601601a892'
down_revision: Union[str, Sequence[str], None] = '9a7a3d60e7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_record', sa.Column('borrower_id', sa.Uuid(), nullable=False), schema='borrow_service')
    op.drop_column('borrow_record', 'borrower_name', schema='borrow_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_record', sa.Column('borrower_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='borrow_service')
    op.drop_column('borrow_record', 'borrower_id', schema='borrow_service')
    # ### end Alembic commands ###
